services:
  db:
    image: postgres:18.3-alpine3.23
    container_name: quickstart-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - quickstart-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      timeout: 5s
      interval: 10s
      retries: 5


  app:
    container_name: quickstart-spring-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quickstart-network
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always

networks:
  quickstart-network:
    driver: bridge