spring.config.import=optional:file:.env[.properties]

# Use this for docker compose run
spring.datasource.url=jdbc:postgresql://db:5432/${DB_NAME}

# Use this for local runs
#spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#Actuators
management.endpoints.web.exposure.include=health,info,metrics

#logger
debug=true
logging.level.org.springframework.security=TRACE